// resuma-routes-fingerprint: 10cf1946acbbbe27
// Auto-generated by `resuma routes --generate`. Do not edit by hand.
use resuma::prelude::*;
use resuma::FlowPageRegistry;

pub struct PagesRegistry;

impl FlowPageRegistry for PagesRegistry {
fn routes(&self) -> &'static [(&'static str, &'static str)] {
&[
                    ("/", "index"),
                    ("/jobs/:id", "jobs::_id_"),
                    ("/logs", "logs"),
                    ("/profile", "profile"),
                    ("/settings", "settings"),
                ]
}

fn layout_for(&self, pattern: &str) -> &'static [&'static str] {
match pattern {
                    "/" => &[],
                    "/jobs/:id" => &[],
                    "/logs" => &[],
                    "/profile" => &[],
                    "/settings" => &[],
                    _ => &[],
}
}

fn render(&self, module: &str, req: FlowRequest) -> Option<View> {
match module {
            "index" => Some(super::index::page(req)),
            "jobs::_id_" => Some(super::jobs::_id_::page(req)),
            "logs" => Some(super::logs::page(req)),
            "profile" => Some(super::profile::page(req)),
            "settings" => Some(super::settings::page(req)),
            _ => None,
}
}
}
