// Auto-generated by `resuma routes --generate`. Do not edit by hand.

pub mod index;
pub mod jobs {
    pub mod _id_;
}
pub mod logs;
pub mod profile;
pub mod settings;

mod _registry;
pub use _registry::PagesRegistry;
